#!/usr/bin/with-contenv bash

# create directories
mkdir -p \
    /config/{log,data/transcodes,cache} \
    /data \
    /transcode

# permissions
chown \
    /config \
    /config/* \
    /config/data/transcodes \
    /transcode
